### ISSUE TITLE
League 2 spain

### ISSUE THREAD

**Issue by villak** [ziko-ZR1/FootOnsat#5]
It is possible to create json of league 2 spain.?
I know that today's matches are there, but only those of the day, and users from Spain would like to have complete information on league 2. Could you create the json for laliga2? If necessary we will mod the plugin and you don't have to include it in the original, if you don't want to. Or if you want to free the api, we extract the json ourselves and upload it to our server. Thank you very much, and congratulations on the great work with the plugin.
Our git https://github.com/OpenSPA/SpaOpenPlugins/tree/master/footonsat/plugin
Greetings @ziko-ZR1 and @fairbird

**Comment by ziko-ZR1** [comment]
we are migrating to a new server at the moment tomorrow till we finish i will provide a new api link with the league 2 , if you need other leagues just tell me .

**Comment by villak** [comment]
Thank you so much for everything!

**Comment by ziko-ZR1** [comment]
league 2 api link:
http://cirtateam.selfip.com/footonsat/api/laliga2.json
