### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by persianpros** [ziko-ZR1/FootOnsat#7]
This commit makes your plugin to compile with py3: https://github.com/persianpros/FootOnsat/commit/232ff75c10c7dc9d0213d3464ecf06390917f70a

You can create a new branch or even better do with six if conditions, sample: https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/lib/python/Components/Converter/SensorToText.py#L17

**Comment by ziko-ZR1** [comment]
Done thank you!!

https://github.com/ziko-ZR1/FootOnsat/commit/d87f923e541c91bb002da216e427fda8e959d759
